import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(new URL('../../pwa/package.json',import.meta.url));const React=require('react');const {transformSync}=require('esbuild');
const raw={programs:[{id:'gym'}],teams:[{id:'team',program_id:'gym'},{id:'other-team',program_id:'other'}],athletes:[{id:'one',team_id:'team'},{id:'two',team_id:'team'},{id:'foreign',team_id:'other-team'}],billing_accounts:[{id:'account-one',athlete_id:'one',season_total:100,paid:150,synced_paid:900},{id:'account-two',athlete_id:'two',season_total:100,paid:50,synced_paid:900},{id:'foreign-account',athlete_id:'foreign',season_total:9999,paid:9999}],billing_charges:[{id:'charge',account_id:'account-one',amount:700,paid_at:'2026-01-01'}],registrations:[{id:'reg',program_id:'gym',status:'accepted',payment_status:'paid',amount_paid_cents:2000},{id:'comp',program_id:'gym',status:'accepted',payment_status:'comped'},{id:'rejected',program_id:'gym',status:'rejected',payment_status:'none'},{id:'foreign-reg',program_id:'other',payment_status:'paid',amount_paid_cents:999999}],class_enrollments:[{id:'enroll-one',program_id:'gym',registration_id:'reg',payment_status:'paid',amount_paid_cents:2000,class_id:'class'},{id:'duplicate-view',program_id:'gym',registration_id:'reg',payment_status:'paid',amount_paid_cents:2000,class_id:'class'}],program_classes:[{id:'class',price_cents:999999}]};
test('owner billing keeps posted ledgers separate and does not offset sibling debt or count mirrored receipts twice',async()=>{
 let session={profile:{program_id:'gym'}};const window={HZdb:{_raw:()=>raw,auth:{_getSession:()=>session}}};
 vm.runInNewContext(fs.readFileSync(new URL('../../pwa/hit_zero_web/db/selectors.js',import.meta.url),'utf8'),{window,Date,console});await window.HZsel._refresh();
 const bill=window.HZsel.programBilling();assert.equal(bill.paid,200);assert.equal(bill.total,200);assert.equal(bill.owed,50);assert.equal(bill.registrationRevenue,20);assert.equal(bill.classRevenue,20);assert.equal(bill.pendingRegistrations,0);assert.equal(bill.syncedPaid,0);
 session={profile:{}};assert.equal(window.HZsel.programBilling().paid,0);assert.equal(window.HZsel.programBilling().registrationRevenue,0);
});
test('parent billing uses only linked accounts and recorded class amounts, independent of catalog changes',()=>{
 const window={HZviewerScope:()=>({visibleAthleteIds:new Set(['one','two'])}),HZsel:{classEnrollmentsForParent:()=>raw.class_enrollments}};const ctx={React,window};
 vm.runInNewContext(transformSync(fs.readFileSync(new URL('../../pwa/hit_zero_web/screens/OtherScreens.jsx',import.meta.url),'utf8'),{loader:'jsx'}).code,ctx);
 const bill=ctx.parentBillingSummary(raw,{profile:{program_id:'gym'}});assert.equal(bill.paid,200);assert.equal(bill.total,200);assert.equal(bill.owed,50);assert.equal(bill.classPaid,20);assert.equal(bill.pendingCount,0);
});
